from __future__ import print_function

__author__ = "Ning Guo, ceguo@connect.ust.hk"
__supervisor__ = "Jidong Zhao, jzhao@ust.hk"
__institution__ = "The Hong Kong University of Science and Technology"

"""
DEM part for multiscale simulation which sets up a packing representing
a material point (RVE) at the Gauss point of the FEM domain and returns
constitutive responses (updated stress and tangent operator) at this point.
"""
# import yade modules
import sys, os
from os.path import expanduser

sys.path.append(expanduser('~') + '/yade/bin')  # path where you have yadeimport.py
# yadeimport.py is generated by `ln yade-versionNo yadeimport.py`
from yadeimport import *
import numpy

Omega().load('./0.yade.gz')

print('stress:\t', getStress())
print('hSize: \t', O.cell.hSize)
